/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, Interface } from "ethers";
import type { ContractRunner } from "ethers/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  PromiseOrValue,
} from "../../common.js";

export interface IERC721ReceiverInterface extends Interface {}

export interface IERC721Receiver extends BaseContract {
  connect(runner: null | ContractRunner): this;

  interface: IERC721ReceiverInterface;
}
