/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, Interface } from "ethers";
import type { ContractRunner } from "ethers/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  PromiseOrValue,
} from "../../common";

export interface NAME12manglingInterface extends Interface {}

export interface NAME12mangling extends BaseContract {
  connect(runner: null | ContractRunner): this;

  interface: NAME12manglingInterface;
}
