/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, Interface, LogDescription } from "ethers";
import type { ContractRunner } from "ethers/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  PromiseOrValue,
} from "../../common";

export interface AInterface extends Interface {}

export interface CommittedEventObject {
  whitelist: string[];
}
export type CommittedEvent = TypedEvent<[string[]], CommittedEventObject> &
  LogDescription;

export type CommittedEventFilter = TypedEventFilter<CommittedEvent>;

export interface A extends BaseContract {
  connect(runner: null | ContractRunner): this;

  interface: AInterface;
}
