/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { DeferredTopicFilter } from "ethers";
import { LogParams } from "ethers/providers";
import { Result } from "ethers";

export interface TypedEvent<
    TArgsArray extends Array<any> = any,
    TArgsObject = any
> extends LogParams {
  args: TArgsArray & TArgsObject & {
    /**
     *  Returns the Result as a normal Array.
     */
    toArray(): Array<any>;
    /**
     *  Returns the Result as an Object with each name-value pair.
     */
    toObject(): Record<string, any>;
  };
  name: string
  /**
   *  Returns the Result as a normal Array.
   */
  toArray(): Array<any>;
  /**
   *  Returns the Result as an Object with each name-value pair.
   */
  toObject(): Record<string, any>;
}

export interface TypedEventFilter<_TEvent extends TypedEvent>
    extends DeferredTopicFilter {}

export type PromiseOrValue<T> = T | Promise<T>;
