/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, Interface } from "ethers";
import type { ContractRunner } from "ethers/providers";
import type { TypedEventFilter, TypedEvent, PromiseOrValue } from "../common";

export interface ISimpleTokenInterface extends Interface {}

export interface ISimpleToken extends BaseContract {
  connect(runner: null | ContractRunner): this;

  interface: ISimpleTokenInterface;
}
