/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, Interface } from "ethers";
import type { ContractRunner } from "ethers/providers";
import type { TypedEventFilter, TypedEvent, PromiseOrValue } from "../common";

export declare namespace Issue552_Observer {
  export type ObservationStruct = {
    val: PromiseOrValue<BigNumberish>;
    blockTimestamp: PromiseOrValue<BigNumberish>;
  };

  export type ObservationStructOutput = [bigint, bigint] & {
    val: bigint;
    blockTimestamp: bigint;
  };
}

export declare namespace Issue552_Reproduction {
  export type ObservationParamsStruct = {
    observations: Issue552_Observer.ObservationStruct[];
    index: PromiseOrValue<BigNumberish>;
  };

  export type ObservationParamsStructOutput = [
    Issue552_Observer.ObservationStructOutput[],
    number
  ] & {
    observations: Issue552_Observer.ObservationStructOutput[];
    index: number;
  };
}

export interface Issue552_ReproductionInterface extends Interface {}

export interface Issue552_Reproduction extends BaseContract {
  connect(runner: null | ContractRunner): this;

  interface: Issue552_ReproductionInterface;
}
